---

- name: Get gradle zip
  get_url: 
    url: https://gradle.org/next-steps/?version=8.3&format=bin
    dest: /

- name: Unzip gradle
  unarchive:
    src: gradle-8.3-bin.zip
    dest: /opt/gradle

- name: Export PATH with gradle
  shell: export PATH=$PATH:/opt/gradle/gradle-8.3/bin
  become: yes
