---

- name:  Get and unzip gradle file
  shell:  wget -c https://services.gradle.org/distributions/gradle-8.3-bin.zip -P /tmp && sudo unzip -d /opt/ /tmp/gradle-*.zip
  become: yes

- name: Add a line to the end of a file
  lineinfile:
    path: /etc/profile
    insertafter: EOF
    line: export PATH=$PATH:/opt/gradle-8.3/bin"
