# CREATE TABLE Image (
#    id BIGINT NOT NULL AUTO_INCREMENT,
#    base64 MEDIUMTEXT NOT NULL,
#    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
#    portfolio_job_id BIGINT,
#    PRIMARY KEY (id)
# );
#
